<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e8e17095-83ec-4ccb-8f1b-b165c730e338</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\POS.Domain\POS.Domain.csproj" />
  </ItemGroup>

</Project>
